### PR TITLE
Add focusable function to API

### PR DESCRIPTION
**Pull request by vonagam**
Add a function to select all focusable elements (not only tabbable ones).

Is there any objections to adding such functionality?

If no, i will proceed to adding simple tests.

### CODE REVIEW

**Comment by stefcameron** [comment]
@vonagam If you're still keen on adding this, I think it makes sense! It's a nice addition to `tabbable` and `isTabbable`. `index.js` has changed a bit since your PR, though, especially to update the exported structure.

**Comment by stefcameron** [comment]
(I just took over as a new maintainer)

**Comment by vonagam** [comment]
Rebased.

**Comment by stefcameron** [comment]
@vonagam Thank you! 😄

**Review by stefcameron — APPROVED** [review]

**Comment by stefcameron** [comment]
I realized we forgot to add tests for `focusable()` so I did in #73.

**Comment by vonagam** [comment]
Ye, was surprised when you merged without a tests/doc request.

Thanks for doing them and sorry for bother.

**Comment by stefcameron** [comment]
I'm still fresh with taking over as maintainer across `tabbable`, `focus-trap`, and `focus-trap-react`... Lots of balls in the air learning the intricacies of each repo and updating them all to more recent dependencies and tooling!

No bother. I didn't think of it and merged your PR, so it was my responsibility to follow-up! I didn't think of typings either... Thanks for #74!

**Pull request merged**
